= Sfera
:author: Marcos Cruz (programandala.net)
:revdate: 2016-02-13

// This file is part of Sfera, a library for SuperForth
// http://programandala.net/en.program.sfera.html

// You may do whatever you want with this work, so long as you
// retain the copyright/authorship/acknowledgment/credit
// notice(s) and this license in all redistributed copies and
// derived works.  There is no warranty.

// This file is written in AsciiDoc/Asciidoctor format
// (http://asciidoctor.org)

Sfera is a library under development for SuperForth, the Forth-83
system written by Gerry Jackson for Sinclair QL, and published by
Digital Precision in 1985.

"Sfera" stands for "SuperForth Enhancements, Resources and Addons".

- http://programandala.net/en.program.sfera.html[Sfera homepage]
- http://programandala.net/en.program.sfera.history.html[Sfera
  development history]

The development is done on a
http://programandala.net/en.computer.raspesis.0x07.html[homemade portable Raspberry Pi 2]
with the
http://raspbian.org[Raspbian]
operating system and
http://www.wlenerz.com/SMSQmulator/[SMSQmulator].

== Directories and files

sfera/:: Main directory.
sfera/README.adoc:: This file.
sfera/TO-DO.adoc:: To-do tasks, unfinished features, known issues.
sfera/LICENSE.txt:: The license.
sfera/VERSIONS.txt:: Versions history.
sfera/boot_fs:: Main file of the library.
sfera/:: Sources of words written in Forth (_fs extension).
sfera/asm/:: Sources of words written in assembly (_asm extension)
and their assembler listings (_asm_lst extension).
sfera/bin/:: Binaries of words written in assembly (_bin extension).

== User configuration

The __boot_fs__ file has a user configuration section at the end,
where default devices, windows and paths are configured.

=== QL devices

By default device _dev4_ is configured as path 1 for Forth sources,
and therefore it must be configured in your QDOS or SMSQ/E system this
way:

----
dev_use 4, "path_to_sfera_"
----

Also device _nfa4_, which is specific of the
http://www.wlenerz.com/SMSQmulator/[SMSQmulator] emulator, is used as
path 3.
